export const employeeData = [
    {
        name:"Rirani",
        empid: "10",
        position : "Cashier",
        branch : "Pondicherry",
        joindate : "2022-02-11",
        salary: 10000,
        gender:"Female",
        dob : "2022-02-18",
        email :"romin.k.irani@gmail.com",
        mobile : 4081234567,
        line1: "No.105 ,  Street address, ",
        line2:"Kottivakkam,",
        city:"Chennai",
        state :"Tamil Nadu",
        zipcode :607105,
        country :"Australia",
        id :Date.now()+0,
    },

    {
        name:"Devid Rome",
        empid: "12",
        position : "Cook",
        branch : "coimbatore",
        joindate : "2022-02-11",
        salary: 15000,
        gender:"Male",
        dob : "2022-02-18",
        email :"devid.rome@learningcontainer.com",
        mobile : 4081111111,
        line1: "No.100 ,  Street address,  ",
        line2:"Kottivakkam,",
        city:"Chennai",
        state :"Kerala",
        zipcode :607105,
        country :"India",
        id :Date.now()+1,
    },

    {
        name:"Tin jonsi",
        empid: "14",
        position : "Chef",
        branch : "Salem",
        joindate : "2022-02-11",
        salary: 20000,
        gender:"Female",
        dob : "2022-02-18",
        email :"tin.jonsi@learningcontainer.com",
        mobile : 4082222222,
        line1: "No.100 ,  Street address,  ",
        line2:"Kottivakkam,",
        city:"Chennai",
        state :"Pondicherry",
        zipcode :607105,
        country :"USA",
        id :Date.now()+2,
    },

    {
        name:"Krish Lee",
        empid: "16",
        position : "Waiter",
        branch : "Chennai",
        joindate : "2022-02-11",
        salary: 12000,
        gender:"Male",
        dob : "2022-02-18",
        email :"krish.lee@learningcontainer.com",
        mobile : 408123456,
        line1: "No.100 ,  Street address,  ",
        line2:"Kottivakkam,",
        city:"Chennai",
        state :"Karnataka",
        zipcode :607105,
        country :"China",
        id :Date.now()+3,
    },
]